services:
  import_definition.process_manager.listener:
    class: ImportDefinitionsBundle\ProcessManager\ProcessManagerListener
    arguments:
      - '@process_manager.factory.process'
      - '@process_manager.process.log'
    tags:
      - { name: 'kernel.event_listener', event: 'import_definition.total',           method: 'onTotalEvent' }
      - { name: 'kernel.event_listener', event: 'import_definition.progress',        method: 'onProgressEvent' }
      - { name: 'kernel.event_listener', event: 'import_definition.status',          method: 'onStatusEvent' }
      - { name: 'kernel.event_listener', event: 'import_definition.finished',        method: 'onFinishedEvent' }
      - { name: 'kernel.event_listener', event: 'import_definition.object.start',    method: 'onObjectStartEvent' }
      - { name: 'kernel.event_listener', event: 'import_definition.object.finished', method: 'onObjectFinishedEvent' }

  import_definition.process_manager.process:
    class: ImportDefinitionsBundle\ProcessManager\ImportDefinitionProcess
    tags:
      - { name: 'process_manager.process', type: 'importdefinition', form-type: ImportDefinitionsBundle\Form\Type\ProcessManager\ImportDefinitionsType }