sudo: false
language: php

addons:
    mariadb: '10.2'
    hosts:
        - pimcore-test.dev

services:
    - mysql

env:
    global:
        - PIMCORE_ENVIRONMENT=test
        - PIMCORE_TEST_DB_DSN="mysql://root@localhost/im_test"
        - PIMCORE_VERSION="~5.8"
        - IM_TEST=1
        - IM_SUITE=application
        - SYMFONY_VERSION="^3.4"

matrix:
    include:
        - sudo: required
          php: 7.1
          env:
            - IM_SUITE=codestyle

        - sudo: required
          php: 7.2
          env:
            - IM_SUITE=stan

        - sudo: required
          php: 7.1
          env:
            - PIMCORE_VERSION="~5.8"

        - sudo: required
          php: 7.2
          env:
            - PIMCORE_VERSION="~5.8"

        - sudo: required
          php: 7.2
          env:
            - PIMCORE_VERSION="~6.0"
            - SYMFONY_VERSION="^4.0"

        - sudo: required
          php: 7.3
          env:
             - PIMCORE_VERSION="~6.0"
             - SYMFONY_VERSION="^4.0"

        - sudo: required
          php: 7.2
          env:
            - PIMCORE_VERSION="dev-master"
            - SYMFONY_VERSION="^4.0"

        - sudo: required
          php: 7.3
          env:
             - PIMCORE_VERSION="dev-master"
             - SYMFONY_VERSION="^4.0"
    allow_failures:
        - env:
            - IM_SUITE=codestyle
        - env:
            - PIMCORE_VERSION="dev-master"
        - env:
            - PIMCORE_VERSION="dev-master"
            - SYMFONY_VERSION="^4.0"
    fast_finish: true

cache:
    directories:
        - $HOME/.cache/composer

install:
    - etc/travis/install

script:
    - etc/travis/script

notifications:
    email:
        - travis-ci@coreshop.org
